//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNLCI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JustificantesVistos
    {
        public int JustificanteVistoID { get; set; }
        public int JustificanteID { get; set; }
        public int DocenteID { get; set; }
        public Nullable<System.DateTime> FechaVisto { get; set; }
        public Nullable<bool> Visto { get; set; }
    
        public virtual Docente Docente { get; set; }
        public virtual Justificante Justificante { get; set; }
    }
}
